version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres-gladiolen
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: gladiolen
    ports:
      - "5432:5432"
