services:
  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: testdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: gladiolen
    ports:
      - "5432:5432"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data

volumes:
  timescaledb-data: